---
title: "My Journey & Interaction with Fish Farmers in Siaya County"
subtitle: "My Personal Experiences"
author: "Dan Mungai"
format: html
toc: true
editor: visual
---

# Preamble

I had the opportunity to interact with fish farmers from the remotest parts of Siaya County specifically in wards named Tingare, Alego Usonga, Kombo and East Alego. The objective of this particular Aquaculture Business Development Project (ABDP) exercise was to verify the the validity and credibility of Small Aquaculture Groups (SAGs) in the pilot counties in which Siaya county is a member. I had the opportunity to interact with fish farmers one on one, directly listen to their challenges, cries, ambitions, aspirations and opinions. It was quite an engaging, illuminating and eye opening experience in which I had the privillege of participating.

This is a blog of my encounters and learning moments from the excursion rather than a professional report. Therefore, the language and style is quite relaxed.

## Journeying

I cannot tell what had happened at Gilgil weighbridge, a traffic snarl up snaked all the way to Naivasha town and all the way to Gilgil junction on Monday 6th June 2022 on my Journey to Siaya. After a full stop snarl up of two hours, I arrived Siaya county early morning ready to embark on the activities of the day. Siaya county to my surprise seemed a little behind economically compared to Homabay county. beautiful wide roads with only two or one vehicle from any end of the road and a couple of motorbikes.

## Encounters with Fish Farmers

### East Alego Fish Farmers Group

*Sisi nakaribisha nyinyi sana kwa hii kikundi yetu ya wakulima ya samaki*. The able chairman exuberantly welcomed a group of three on a **KIBO** motorbike in the chiefs compound where the group had assembled. The county fisheries officer welcomed me for interviews after a few introductions and commonalities.

*Niko hapa kuhakikisha ya kwamba nyinyi ni watu wa kikundi cha kweli, Kwamba kikundi hiki kimesajiriwa na serikali na kwa hivyo mko na cheti cha usajili, kwamba mna uongozi mzuri, kuwa mna vijana na akina mama katika kikundi chenu. Hii ni ili mpate kufaidika na yanayopangwa na program ya ABDP. Kwa hivyo naomba mnipe ruhusa ya kuwauliza maswali yatakayochukua dakika chache.* The interview took a few minutes and before long it was time for questions, concerns, opinion or suggestions.

farmer 1: *Mimi niko na swali, ningetaka kujua serikali iko na mpango gani kuhusu sisi. Kwa kuwa vile mambo inatendeka sasa si mzuri. Mimi nilipata net ndogo sana na ya quality ya chini ambayo haiwezi saidia mimi. Mko na mpango kama ile ya Kibaki? Yeye alisaidia sisi kutengeneza pond, halafu akapea sisi samaki. Sasa ile inasaidia sisi ni ile ya kibaki. Hii sasa vile inakuja, inapewa watu wengine, mimi sipendi*

I had no answer to this concerned farmer. Therefore I shifted the question to the PFT of Siaya. He answered the question to their satisfaction by explaining to the them the plan of the ABDP program. The explanation was done in Dholuo. All I could was to attentively listen but hear nothing while just enjoying the beauty of the language.

Farmer 2: "We were given fishing nets as a group. Due to the numbers in the group it has become difficult to use the net among the group members since it is only one. Would it be possible for every member in the group to get a net of their own" - This question was asked by a young member of the group who happened to be the secretary of the group. The able chairman applauded her as an able secretary.

We noted the concern as the county fisheries representative again addressed the concern in Dholuo.

Farmer 3: *Sisi hapana iko na uwezo ya kuchimba pond. Kuna uwezekano au mpango ya serikali kusaidia sisi kutengeneza pond kwa kuwa hakuna nguvu kwa sisi?*

Chairperson: Our other major problem is fish feeds. *Sisi anaweka samaki lakini hakuna chakula ya kupea hawa. Wakati mwingine hatuna hata* fish seeds. *Tunawezakuwa na pesa lakini chakula yenyewe hatuna mahali pa kununua. Saidia sisi hapo*

The concern and opinion was noted in a field book. The group was so kind that they offered us refreshments to cool down from our weary journey

The group bade us farewell as we sped away on the new giant Kibo motorbike.

### Kadenge Fish Farmers

Kadenge fish famers' group happened to be the most organised and professional group of all the groups I met. The secretary read the last meeting's minutes, gave an elaborate overview of the group in terms of the number of members, their gender and age distribution, their action plan, vision and long term objectives. Surprisingly the leader of the group happened to be the youngest of the group. The governance of the group could be highly attributed to that young man.

The interaction was immensely illuminating as described by the farmers.

Kadenge farmer 1: *Hapa shida yetu kubwa ni maji. Hapa mvua hainyeshi sana kwa hivyo pond hukauka kabisa. Tuko na pump moja ambayo sisi wote tunatumia. Kwa kuwa sisi ni wengi na kwa jumla tuna ponds 101 inakuwa vigumu hiyo pump kutusaidia. Je serikali inawezafanyia sisi mpango aone vile anaweza tusaidia njia ya kupump maji kwa ponds zetu tuzuie kukauka?* another farmer interjected,

Kadenge farmer 2: *Sida ya hapa ni mchanga ya hapa. Mchanga ya hapo haiweki maji. Maji inapotea kwa mchanga haraka. Hii mchanga yetu anakunywa maji sana halafu wakati wa kiangazi pond anakauka kabisa* The chairperson then interjected

Kadenge chairperson: *Kwa ajili ya kiangazi na hii mchanga yetu mbaya, kitu inawezakuwa muhimu kwetu ni liner. Hii liner itazuia maji kupotea. Kama serikali anaweza pea sisi liner, atasaidia sisi sana*

Kadenge Treasurer: You know another problem we have is predators. Predator nets would help us a lot. we are loosing so many fish even big ones from our ponds.

The farmers seemed to have been excited by this issue of bird predators.

Another farmer who was silent before quickly interjected.

Kadenge farmer 3: *Hawa ndege wakati mwingine wanakuja kama mia moja kwa pond yako. Mia moja au zaidi wanakula samaki kiasi kama hii* the farmer said while gesturing with his arm. *Wanaweza kula samaki kwa pond karibu anamaliza yote.* The farmers all together enthusiastically agreed with him as they digressed into dholuo explaining their predicament. Unfortunately I could not tell what he was saying but I could see and feel his emotional pain. The farmer looked at me as a savior from his woes.

After so much conversations we left them with a little bit of hope that something would be done. The county representative advised them to seek solutions within the group. The treasurer concluded before we left;

Kadenge Treasurer: *Shida ingine kubwa ni fish feeds.* They are very expensive and scarcely found. *Iko mbali sana na hata haipatikani.* Our formulated feeds *Inafanya samaki wetu akuwe na* stunted growth. *Hapo sijui sirikali atasaidia sisi namna gani*

### Kombo Fish Farmers

Kombo beach fish farmers' group is located at the beach of the satellite lake of Lake Victoria called Lake Kanyaboli in that particular beach called Kombo which is one of the seven beaches of the lake.

The cry of this group was majorly on illegal gears employed by other beaches and the use of a huge club to scare the fish to enter in fishing nets.

Chairperson: This beach is hated and discriminated for use of right and legal gears in fishing. Due to the diligence of this group, we are not obligated to bribe anyone and thus we are hated. We do not receive any help due to that we do not pay bribes.

Kombo Farmer: *Hii Lake yetu anamalizwa na illegal gears na officers wa county wanajua. Tulienda kwa county director na hakusaidia sisi*

The farmers made some comments that I prefer not to document. The cry of farmers in Kombo beach is painful. Their livelihood is almost gone.

### Tingare Banana Food Security SHG

I do not have nice or learning moments from this group and therefore would have nothing to report. The group had all the necessary documentation and that ends there.

         **Looking Forward for other Field Engagements with Farmers**

                                       **The End**
